### ISSUE TITLE
Vanilla JS Version

### ISSUE THREAD

**Issue by anubra266** [ChristineTham/chakra-components#1]
Showed this to someone, but he's ugly at Ts. 
For those really bad at Typescript or not comfortable with, do you mind me working on a pure JS version.

**Comment by ChristineTham** [comment]
> Showed this to someone, but he's ugly at Ts.
> For those really bad at Typescript or not comfortable with, do you mind me working on a pure JS version.

Probably best to wait as the site will undergo a lot of changes in the next few days. I am hoping to make the components more usable in projects (support variants and colorschemes etc.).

**Comment by anubra266** [comment]
Cool. I'll wait then. Godspeed!

**Comment by ChristineTham** [comment]
> Cool. I'll wait then. Godspeed!

You should tell your friend to start learning Typescript. Saves a lot of time debugging errors!

**Comment by anubra266** [comment]
> > Cool. I'll wait then. Godspeed!
> 
> You should tell your friend to start learning Typescript. Saves a lot of time debugging errors!

I'll do that. ☺
